esphome:
  name: "levoit-air-purifier"
  friendly_name: "levoit-air-purifier"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

external_components:
  - source: github://acvigue/esphome-levoit-purifier
    components: [levoit]

logger:
  baud_rate: 115200

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  ap:
    ssid: "Levoit-Core300S Fallback Hotspot"
    password: !secret ap_password

captive_portal:

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

levoit:
  id: levoit1
#  model: core300s  # default core300s, note: this config also works for core400s
#  command_delay: 300 # default 300
#  command_timeout: 200 # default 200
#  status_poll_seconds: 0 # default 0, not needed if you get auto status msgs

fan:
  - platform: levoit
    name: "Levoit Purifier"

sensor:
#   Uptime sensor.
#  - platform: uptime
#    name: Uptime

#   WiFi Signal sensor.
#  - platform: wifi_signal
#    name: WiFi Signal
#    update_interval: 60s

  # PM2.5 sensor
  - platform: levoit
    pm_2_5:
      name: "PM2.5"
    air_quality:
      name: "Air Quality Index"

switch:
  - platform: levoit
    display_lock:
      name: "Display Lock"
    display_on:
      name: "Display On"
    power:
      name: "Master Power"

button:
  - platform: levoit
    filter_reset:
      name: "Filter Reset"

select:
  - platform: levoit
    auto_mode:
      name: "Auto Mode"
    # Optional: fan_mode is available via the fan entity
    # fan_mode:
    #   name: "Fan Mode"